In [1]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
import pandas as pd
import numpy as np
from matplotlib import cm, pyplot as plt
from matplotlib.dates import YearLocator, MonthLocator
from hmmlearn.hmm import GMMHMM

btc = pd.read_csv('./data/bitcoin_price.csv')

btc.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Volume</th>
      <th>Market Cap</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Nov 07, 2017</td>
      <td>7023.10</td>
      <td>7253.32</td>
      <td>7023.10</td>
      <td>7144.38</td>
      <td>2,326,340,000</td>
      <td>117,056,000,000</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Nov 06, 2017</td>
      <td>7403.22</td>
      <td>7445.77</td>
      <td>7007.31</td>
      <td>7022.76</td>
      <td>3,111,900,000</td>
      <td>123,379,000,000</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Nov 05, 2017</td>
      <td>7404.52</td>
      <td>7617.48</td>
      <td>7333.19</td>
      <td>7407.41</td>
      <td>2,380,410,000</td>
      <td>123,388,000,000</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Nov 04, 2017</td>
      <td>7164.48</td>
      <td>7492.86</td>
      <td>7031.28</td>
      <td>7379.95</td>
      <td>2,483,800,000</td>
      <td>119,376,000,000</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Nov 03, 2017</td>
      <td>7087.53</td>
      <td>7461.29</td>
      <td>7002.94</td>
      <td>7207.76</td>
      <td>3,369,860,000</td>
      <td>118,084,000,000</td>
    </tr>
  </tbody>
</table>
</div>

In [2]:
btc = btc.iloc[::-1]

btc.head()

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Date</th>
      <th>Open</th>
      <th>High</th>
      <th>Low</th>
      <th>Close</th>
      <th>Volume</th>
      <th>Market Cap</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1654</th>
      <td>Apr 28, 2013</td>
      <td>135.30</td>
      <td>135.98</td>
      <td>132.10</td>
      <td>134.21</td>
      <td>-</td>
      <td>1,500,520,000</td>
    </tr>
    <tr>
      <th>1653</th>
      <td>Apr 29, 2013</td>
      <td>134.44</td>
      <td>147.49</td>
      <td>134.00</td>
      <td>144.54</td>
      <td>-</td>
      <td>1,491,160,000</td>
    </tr>
    <tr>
      <th>1652</th>
      <td>Apr 30, 2013</td>
      <td>144.00</td>
      <td>146.93</td>
      <td>134.05</td>
      <td>139.00</td>
      <td>-</td>
      <td>1,597,780,000</td>
    </tr>
    <tr>
      <th>1651</th>
      <td>May 01, 2013</td>
      <td>139.00</td>
      <td>139.89</td>
      <td>107.72</td>
      <td>116.99</td>
      <td>-</td>
      <td>1,542,820,000</td>
    </tr>
    <tr>
      <th>1650</th>
      <td>May 02, 2013</td>
      <td>116.38</td>
      <td>125.60</td>
      <td>92.28</td>
      <td>105.21</td>
      <td>-</td>
      <td>1,292,190,000</td>
    </tr>
  </tbody>
</table>
</div>

In [155]:
features = btc[["Open","High","Low","Close"]].values

features[:4]

array([[ 2.83    ,  3.54    ,  2.52    ,  2.77    ],
       [ 2.79    ,  2.8     ,  0.714725,  0.753325],
       [ 0.706136,  0.87981 ,  0.629191,  0.701897],
       [ 0.713989,  0.729854,  0.636546,  0.708448]])

In [156]:
fracChange = ((features[:,3]/features[:,0]) - 1)*100
fracHigh   = ((features[:,1]/features[:,0]) - 1)*100
fracLow    = (1 - (features[:,2]/features[:,0]))*100

X = np.column_stack([fracChange, fracHigh, fracLow])

train = X[:1647]
train[:4]

array([[ -2.12014134,  25.08833922,  10.9540636 ],
       [-72.99910394,   0.35842294,  74.38261649],
       [ -0.60030929,  24.59497887,  10.89662615],
       [ -0.77606238,   2.22202303,  10.84652565]])

In [157]:
model = GMMHMM(n_components=4, n_mix=6, n_iter=400, tol=0.001, verbose=True)
model.fit(train)

         1       -8323.2364             +nan
/usr/local/lib/python3.6/site-packages/hmmlearn/hmm.py:593: RuntimeWarning: divide by zero encountered in log
  lgmm_posteriors = (np.log(g.predict_proba(X))
         2       -6853.3234       +1469.9131
         3       -6564.9478        +288.3755
         4       -6375.9287        +189.0191
         5       -6256.0973        +119.8314
         6       -6192.5620         +63.5353
         7       -6151.0427         +41.5193
         8       -6118.2815         +32.7611
         9       -6092.3428         +25.9388
        10       -6073.4782         +18.8645
        11       -6056.1759         +17.3023
        12       -6034.8311         +21.3448
        13       -6010.7506         +24.0806
        14       -5992.1922         +18.5583
        15       -5978.2728         +13.9195
/usr/local/lib/python3.6/site-packages/hmmlearn/base.py:459: RuntimeWarning: divide by zero encountered in log
  np.log(self.startprob_),
/usr/local/lib/python3.6/site

        16       -5961.5420         +16.7308
        17       -5941.2905         +20.2514
        18       -5923.4900         +17.8006
        19       -5904.6836         +18.8063
        20       -5882.8518         +21.8318
        21       -5863.7382         +19.1136
        22       -5852.9726         +10.7656
        23       -5848.1339          +4.8387
        24       -5844.9397          +3.1941
        25       -5842.4358          +2.5039
        26       -5840.3495          +2.0863
        27       -5838.5724          +1.7772
        28       -5837.0540          +1.5184
        29       -5835.7608          +1.2932
        30       -5834.6649          +1.0959
        31       -5833.7406          +0.9243


        32       -5832.9614          +0.7792
        33       -5832.2908          +0.6707
        34       -5831.6274          +0.6633
        35       -5830.5160          +1.1114
        36       -5827.2624          +3.2537
        37       -5819.3461          +7.9163
        38       -5807.0424         +12.3037
        39       -5794.1118         +12.9306
        40       -5788.3045          +5.8073
        41       -5782.8138          +5.4906
        42       -5776.9658          +5.8480
        43       -5770.2051          +6.7607
        44       -5762.1630          +8.0421
        45       -5752.7088          +9.4542
        46       -5743.0612          +9.6476
        47       -5734.6104          +8.4508
        48       -5726.4847          +8.1257
        49       -5718.1866          +8.2982
        50       -5709.6097          +8.5769
        51       -5701.8336          +7.7761


        52       -5697.3817          +4.4519
        53       -5694.5251          +2.8566
        54       -5692.1716          +2.3535
        55       -5689.2462          +2.9253
        56       -5682.3301          +6.9161
        57       -5675.5932          +6.7369
        58       -5670.6210          +4.9722
        59       -5664.0687          +6.5523
        60       -5656.3847          +7.6839
        61       -5649.3730          +7.0117
        62       -5647.2861          +2.0869
        63       -5646.0955          +1.1906
        64       -5644.5869          +1.5086
        65       -5641.8636          +2.7232
        66       -5639.4568          +2.4068
        67       -5637.9185          +1.5383
        68       -5637.2634          +0.6551
        69       -5637.0685          +0.1949
        70       -5636.9699          +0.0986
        71       -5636.8954          +0.0745
        72       -5636.8262          +0.0693


        73       -5636.7542          +0.0720
        74       -5636.6772          +0.0770
        75       -5636.5971          +0.0801
        76       -5636.5188          +0.0783
        77       -5636.4474          +0.0714
        78       -5636.3862          +0.0612
        79       -5636.3361          +0.0501
        80       -5636.2959          +0.0402
        81       -5636.2637          +0.0322
        82       -5636.2375          +0.0262
        83       -5636.2157          +0.0218
        84       -5636.1970          +0.0187
        85       -5636.1806          +0.0164
        86       -5636.1657          +0.0149
        87       -5636.1518          +0.0139
        88       -5636.1385          +0.0133
        89       -5636.1252          +0.0132
        90       -5636.1118          +0.0135
        91       -5636.0976          +0.0142
        92       -5636.0823          +0.0153


        93       -5636.0652          +0.0170
        94       -5636.0459          +0.0193
        95       -5636.0238          +0.0221
        96       -5635.9986          +0.0252
        97       -5635.9705          +0.0281
        98       -5635.9402          +0.0303
        99       -5635.9088          +0.0314
       100       -5635.8777          +0.0311
       101       -5635.8474          +0.0303
       102       -5635.8179          +0.0295
       103       -5635.7886          +0.0293
       104       -5635.7587          +0.0299
       105       -5635.7279          +0.0308
       106       -5635.6959          +0.0320
       107       -5635.6629          +0.0330
       108       -5635.6291          +0.0338
       109       -5635.5950          +0.0342
       110       -5635.5607          +0.0343
       111       -5635.5264          +0.0342
       112       -5635.4922          +0.0342
       113       -5635.4578          +0.0344
       114       -5635.4227          +0.0351


       115       -5635.3858          +0.0369
       116       -5635.3452          +0.0406
       117       -5635.2968          +0.0484
       118       -5635.2307          +0.0660
       119       -5635.1169          +0.1138
       120       -5634.8239          +0.2930
       121       -5633.6069          +1.2170
       122       -5630.2589          +3.3480
       123       -5629.0794          +1.1795
       124       -5628.6070          +0.4723
       125       -5628.5057          +0.1013
       126       -5628.4633          +0.0425
       127       -5628.4299          +0.0334
       128       -5628.4009          +0.0290
       129       -5628.3748          +0.0261
       130       -5628.3508          +0.0239
       131       -5628.3290          +0.0218
       132       -5628.3095          +0.0195
       133       -5628.2927          +0.0168
       134       -5628.2787          +0.0140
       135       -5628.2674          +0.0113


       136       -5628.2586          +0.0088
       137       -5628.2519          +0.0067
       138       -5628.2468          +0.0050
       139       -5628.2431          +0.0038
       140       -5628.2403          +0.0028
       141       -5628.2383          +0.0020
       142       -5628.2368          +0.0015
       143       -5628.2358          +0.0010
       144       -5628.2351          +0.0007


GMMHMM(algorithm='viterbi', covariance_type='diag', covars_prior=0.01,
    init_params='stmcw', n_components=4, n_iter=400, n_mix=6,
    params='stmcw', random_state=None, startprob_prior=1.0, tol=0.001,
    transmat_prior=1.0, verbose=True)

In [158]:
predFracChange = np.linspace(-0.1, 0.1, num=50)
predFracHigh   = np.linspace(0, 0.1, num=10)
predFracLow    = np.linspace(0, 0.1, num=10)

observations = []
for i in predFracChange:
    for j in predFracHigh:
        for k in predFracLow:
            observations.append([i, j, k])

observations = np.array(observations)
observations[:4]

array([[-0.1       ,  0.        ,  0.        ],
       [-0.1       ,  0.        ,  0.01111111],
       [-0.1       ,  0.        ,  0.02222222],
       [-0.1       ,  0.        ,  0.03333333]])

In [133]:
observationSeq = train[-10:]
observationSeq

array([[  5.80477222e-01,   2.53303267e+02,   2.50528950e+02],
       [ -4.67808358e-01,   2.50655992e+02,   2.54047271e+02],
       [ -1.26007326e+00,   2.51158675e+02,   2.54554279e+02],
       [ -6.88869720e+00,   2.50000000e+02,   2.57267097e+02],
       [  4.09441408e+00,   2.54158310e+02,   2.52293741e+02],
       [  2.72932089e+00,   2.53981419e+02,   2.50465035e+02],
       [ -2.01432606e+00,   2.51502609e+02,   2.52897077e+02],
       [ -6.00053215e-01,   2.51535984e+02,   2.51704096e+02],
       [  6.94090129e+00,   2.58711013e+02,   2.50518904e+02],
       [  2.56424933e-01,   2.51637653e+02,   2.51210169e+02]])

In [159]:
score = -9999999
best = []
for i in observations:
    seq = observationSeq
    np.vstack([seq, i])
    s = model.score(seq)
    #print(s)
    if(s >= score):
        best = i
        score = s
        print(best, score)

/usr/local/lib/python3.6/site-packages/hmmlearn/base.py:459: RuntimeWarning: divide by zero encountered in log
  np.log(self.startprob_),


[-0.1  0.   0. ] -4093.33110908
[-0.1         0.          0.01111111] -4093.33110908
[-0.1         0.          0.02222222] -4093.33110908
[-0.1         0.          0.03333333] -4093.33110908
[-0.1         0.          0.04444444] -4093.33110908
[-0.1         0.          0.05555556] -4093.33110908
[-0.1         0.          0.06666667] -4093.33110908
[-0.1         0.          0.07777778] -4093.33110908
[-0.1         0.          0.08888889] -4093.33110908
[-0.1  0.   0.1] -4093.33110908
[-0.1         0.01111111  0.        ] -4093.33110908
[-0.1         0.01111111  0.01111111] -4093.33110908
[-0.1         0.01111111  0.02222222] -4093.33110908
[-0.1         0.01111111  0.03333333] -4093.33110908
[-0.1         0.01111111  0.04444444] -4093.33110908
[-0.1         0.01111111  0.05555556] -4093.33110908
[-0.1         0.01111111  0.06666667] -4093.33110908
[-0.1         0.01111111  0.07777778] -4093.33110908
[-0.1         0.01111111  0.08888889] -4093.33110908
[-0.1         0.01111111  0.1      


[-0.1         0.1         0.08888889] -4093.33110908
[-0.1  0.1  0.1] -4093.33110908
[-0.09591837  0.          0.        ] -4093.33110908
[-0.09591837  0.          0.01111111] -4093.33110908
[-0.09591837  0.          0.02222222] -4093.33110908
[-0.09591837  0.          0.03333333] -4093.33110908
[-0.09591837  0.          0.04444444] -4093.33110908
[-0.09591837  0.          0.05555556] -4093.33110908
[-0.09591837  0.          0.06666667] -4093.33110908
[-0.09591837  0.          0.07777778] -4093.33110908
[-0.09591837  0.          0.08888889] -4093.33110908
[-0.09591837  0.          0.1       ] -4093.33110908
[-0.09591837  0.01111111  0.        ] -4093.33110908
[-0.09591837  0.01111111  0.01111111] -4093.33110908
[-0.09591837  0.01111111  0.02222222] -4093.33110908
[-0.09591837  0.01111111  0.03333333] -4093.33110908
[-0.09591837  0.01111111  0.04444444] -4093.33110908
[-0.09591837  0.01111111  0.05555556] -4093.33110908
[-0.09591837  0.01111111  0.06666667] -4093.33110908
[-0.09591837 

[-0.09591837  0.07777778  0.06666667] -4093.33110908
[-0.09591837  0.07777778  0.07777778] -4093.33110908
[-0.09591837  0.07777778  0.08888889] -4093.33110908
[-0.09591837  0.07777778  0.1       ] -4093.33110908
[-0.09591837  0.08888889  0.        ] -4093.33110908
[-0.09591837  0.08888889  0.01111111] -4093.33110908
[-0.09591837  0.08888889  0.02222222] -4093.33110908
[-0.09591837  0.08888889  0.03333333] -4093.33110908
[-0.09591837  0.08888889  0.04444444] -4093.33110908
[-0.09591837  0.08888889  0.05555556] -4093.33110908
[-0.09591837  0.08888889  0.06666667] -4093.33110908
[-0.09591837  0.08888889  0.07777778] -4093.33110908
[-0.09591837  0.08888889  0.08888889] -4093.33110908
[-0.09591837  0.08888889  0.1       ] -4093.33110908
[-0.09591837  0.1         0.        ] -4093.33110908
[-0.09591837  0.1         0.01111111] -4093.33110908
[-0.09591837  0.1         0.02222222] -4093.33110908
[-0.09591837  0.1         0.03333333] -4093.33110908
[-0.09591837  0.1         0.04444444] -4093.33

[-0.09183673  0.1         0.1       ] -4093.33110908
[-0.0877551  0.         0.       ] -4093.33110908
[-0.0877551   0.          0.01111111] -4093.33110908
[-0.0877551   0.          0.02222222] -4093.33110908
[-0.0877551   0.          0.03333333] -4093.33110908
[-0.0877551   0.          0.04444444] -4093.33110908
[-0.0877551   0.          0.05555556] -4093.33110908
[-0.0877551   0.          0.06666667] -4093.33110908
[-0.0877551   0.          0.07777778] -4093.33110908
[-0.0877551   0.          0.08888889] -4093.33110908
[-0.0877551  0.         0.1      ] -4093.33110908
[-0.0877551   0.01111111  0.        ] -4093.33110908
[-0.0877551   0.01111111  0.01111111] -4093.33110908
[-0.0877551   0.01111111  0.02222222] -4093.33110908
[-0.0877551   0.01111111  0.03333333] -4093.33110908
[-0.0877551   0.01111111  0.04444444] -4093.33110908
[-0.0877551   0.01111111  0.05555556] -4093.33110908
[-0.0877551   0.01111111  0.06666667] -4093.33110908
[-0.0877551   0.01111111  0.07777778] -4093.33110908

[-0.0877551   0.03333333  0.02222222] -4093.33110908
[-0.0877551   0.03333333  0.03333333] -4093.33110908
[-0.0877551   0.03333333  0.04444444] -4093.33110908
[-0.0877551   0.03333333  0.05555556] -4093.33110908
[-0.0877551   0.03333333  0.06666667] -4093.33110908
[-0.0877551   0.03333333  0.07777778] -4093.33110908
[-0.0877551   0.03333333  0.08888889] -4093.33110908
[-0.0877551   0.03333333  0.1       ] -4093.33110908
[-0.0877551   0.04444444  0.        ] -4093.33110908
[-0.0877551   0.04444444  0.01111111] -4093.33110908
[-0.0877551   0.04444444  0.02222222] -4093.33110908
[-0.0877551   0.04444444  0.03333333] -4093.33110908
[-0.0877551   0.04444444  0.04444444] -4093.33110908
[-0.0877551   0.04444444  0.05555556] -4093.33110908
[-0.0877551   0.04444444  0.06666667] -4093.33110908
[-0.0877551   0.04444444  0.07777778] -4093.33110908
[-0.0877551   0.04444444  0.08888889] -4093.33110908
[-0.0877551   0.04444444  0.1       ] -4093.33110908
[-0.0877551   0.05555556  0.        ] -4093.33

[-0.0877551   0.07777778  0.06666667] -4093.33110908
[-0.0877551   0.07777778  0.07777778] -4093.33110908
[-0.0877551   0.07777778  0.08888889] -4093.33110908
[-0.0877551   0.07777778  0.1       ] -4093.33110908
[-0.0877551   0.08888889  0.        ] -4093.33110908
[-0.0877551   0.08888889  0.01111111] -4093.33110908
[-0.0877551   0.08888889  0.02222222] -4093.33110908
[-0.0877551   0.08888889  0.03333333] -4093.33110908
[-0.0877551   0.08888889  0.04444444] -4093.33110908
[-0.0877551   0.08888889  0.05555556] -4093.33110908
[-0.0877551   0.08888889  0.06666667] -4093.33110908
[-0.0877551   0.08888889  0.07777778] -4093.33110908
[-0.0877551   0.08888889  0.08888889] -4093.33110908
[-0.0877551   0.08888889  0.1       ] -4093.33110908
[-0.0877551  0.1        0.       ] -4093.33110908
[-0.0877551   0.1         0.01111111] -4093.33110908
[-0.0877551   0.1         0.02222222] -4093.33110908
[-0.0877551   0.1         0.03333333] -4093.33110908
[-0.0877551   0.1         0.04444444] -4093.33110

[-0.08367347  0.01111111  0.01111111] -4093.33110908
[-0.08367347  0.01111111  0.02222222] -4093.33110908
[-0.08367347  0.01111111  0.03333333] -4093.33110908
[-0.08367347  0.01111111  0.04444444] -4093.33110908
[-0.08367347  0.01111111  0.05555556] -4093.33110908
[-0.08367347  0.01111111  0.06666667] -4093.33110908
[-0.08367347  0.01111111  0.07777778] -4093.33110908
[-0.08367347  0.01111111  0.08888889] -4093.33110908
[-0.08367347  0.01111111  0.1       ] -4093.33110908
[-0.08367347  0.02222222  0.        ] -4093.33110908
[-0.08367347  0.02222222  0.01111111] -4093.33110908
[-0.08367347  0.02222222  0.02222222] -4093.33110908
[-0.08367347  0.02222222  0.03333333] -4093.33110908
[-0.08367347  0.02222222  0.04444444] -4093.33110908
[-0.08367347  0.02222222  0.05555556] -4093.33110908
[-0.08367347  0.02222222  0.06666667] -4093.33110908
[-0.08367347  0.02222222  0.07777778] -4093.33110908
[-0.08367347  0.02222222  0.08888889] -4093.33110908
[-0.08367347  0.02222222  0.1       ] -4093.33

[-0.08367347  0.08888889  0.02222222] -4093.33110908
[-0.08367347  0.08888889  0.03333333] -4093.33110908
[-0.08367347  0.08888889  0.04444444] -4093.33110908
[-0.08367347  0.08888889  0.05555556] -4093.33110908
[-0.08367347  0.08888889  0.06666667] -4093.33110908
[-0.08367347  0.08888889  0.07777778] -4093.33110908
[-0.08367347  0.08888889  0.08888889] -4093.33110908
[-0.08367347  0.08888889  0.1       ] -4093.33110908
[-0.08367347  0.1         0.        ] -4093.33110908
[-0.08367347  0.1         0.01111111] -4093.33110908
[-0.08367347  0.1         0.02222222] -4093.33110908
[-0.08367347  0.1         0.03333333] -4093.33110908
[-0.08367347  0.1         0.04444444] -4093.33110908
[-0.08367347  0.1         0.05555556] -4093.33110908
[-0.08367347  0.1         0.06666667] -4093.33110908
[-0.08367347  0.1         0.07777778] -4093.33110908
[-0.08367347  0.1         0.08888889] -4093.33110908
[-0.08367347  0.1         0.1       ] -4093.33110908
[-0.07959184  0.          0.        ] -4093.33


[-0.07959184  0.06666667  0.06666667] -4093.33110908
[-0.07959184  0.06666667  0.07777778] -4093.33110908
[-0.07959184  0.06666667  0.08888889] -4093.33110908
[-0.07959184  0.06666667  0.1       ] -4093.33110908
[-0.07959184  0.07777778  0.        ] -4093.33110908
[-0.07959184  0.07777778  0.01111111] -4093.33110908
[-0.07959184  0.07777778  0.02222222] -4093.33110908
[-0.07959184  0.07777778  0.03333333] -4093.33110908
[-0.07959184  0.07777778  0.04444444] -4093.33110908
[-0.07959184  0.07777778  0.05555556] -4093.33110908
[-0.07959184  0.07777778  0.06666667] -4093.33110908
[-0.07959184  0.07777778  0.07777778] -4093.33110908
[-0.07959184  0.07777778  0.08888889] -4093.33110908
[-0.07959184  0.07777778  0.1       ] -4093.33110908
[-0.07959184  0.08888889  0.        ] -4093.33110908
[-0.07959184  0.08888889  0.01111111] -4093.33110908
[-0.07959184  0.08888889  0.02222222] -4093.33110908
[-0.07959184  0.08888889  0.03333333] -4093.33110908
[-0.07959184  0.08888889  0.04444444] -4093.3

[-0.0755102   0.          0.06666667] -4093.33110908
[-0.0755102   0.          0.07777778] -4093.33110908
[-0.0755102   0.          0.08888889] -4093.33110908
[-0.0755102  0.         0.1      ] -4093.33110908
[-0.0755102   0.01111111  0.        ] -4093.33110908
[-0.0755102   0.01111111  0.01111111] -4093.33110908
[-0.0755102   0.01111111  0.02222222] -4093.33110908
[-0.0755102   0.01111111  0.03333333] -4093.33110908
[-0.0755102   0.01111111  0.04444444] -4093.33110908
[-0.0755102   0.01111111  0.05555556] -4093.33110908
[-0.0755102   0.01111111  0.06666667] -4093.33110908
[-0.0755102   0.01111111  0.07777778] -4093.33110908
[-0.0755102   0.01111111  0.08888889] -4093.33110908
[-0.0755102   0.01111111  0.1       ] -4093.33110908
[-0.0755102   0.02222222  0.        ] -4093.33110908
[-0.0755102   0.02222222  0.01111111] -4093.33110908
[-0.0755102   0.02222222  0.02222222] -4093.33110908
[-0.0755102   0.02222222  0.03333333] -4093.33110908
[-0.0755102   0.02222222  0.04444444] -4093.33110

[-0.06734694  0.03333333  0.01111111] -4093.33110908
[-0.06734694  0.03333333  0.02222222] -4093.33110908
[-0.06734694  0.03333333  0.03333333] -4093.33110908
[-0.06734694  0.03333333  0.04444444] -4093.33110908
[-0.06734694  0.03333333  0.05555556] -4093.33110908
[-0.06734694  0.03333333  0.06666667] -4093.33110908
[-0.06734694  0.03333333  0.07777778] -4093.33110908
[-0.06734694  0.03333333  0.08888889] -4093.33110908
[-0.06734694  0.03333333  0.1       ] -4093.33110908
[-0.06734694  0.04444444  0.        ] -4093.33110908
[-0.06734694  0.04444444  0.01111111] -4093.33110908
[-0.06734694  0.04444444  0.02222222] -4093.33110908
[-0.06734694  0.04444444  0.03333333] -4093.33110908
[-0.06734694  0.04444444  0.04444444] -4093.33110908
[-0.06734694  0.04444444  0.05555556] -4093.33110908
[-0.06734694  0.04444444  0.06666667] -4093.33110908
[-0.06734694  0.04444444  0.07777778] -4093.33110908
[-0.06734694  0.04444444  0.08888889] -4093.33110908
[-0.06734694  0.04444444  0.1       ] -4093.33

 -4093.33110908
[-0.06326531  0.          0.08888889] -4093.33110908
[-0.06326531  0.          0.1       ] -4093.33110908
[-0.06326531  0.01111111  0.        ] -4093.33110908
[-0.06326531  0.01111111  0.01111111] -4093.33110908
[-0.06326531  0.01111111  0.02222222] -4093.33110908
[-0.06326531  0.01111111  0.03333333] -4093.33110908
[-0.06326531  0.01111111  0.04444444] -4093.33110908
[-0.06326531  0.01111111  0.05555556] -4093.33110908
[-0.06326531  0.01111111  0.06666667] -4093.33110908
[-0.06326531  0.01111111  0.07777778] -4093.33110908
[-0.06326531  0.01111111  0.08888889] -4093.33110908
[-0.06326531  0.01111111  0.1       ] -4093.33110908
[-0.06326531  0.02222222  0.        ] -4093.33110908
[-0.06326531  0.02222222  0.01111111] -4093.33110908
[-0.06326531  0.02222222  0.02222222] -4093.33110908
[-0.06326531  0.02222222  0.03333333] -4093.33110908
[-0.06326531  0.02222222  0.04444444] -4093.33110908
[-0.06326531  0.02222222  0.05555556] -4093.33110908
[-0.06326531  0.02222222  0.06

 -4093.33110908
[-0.06326531  0.1         0.06666667] -4093.33110908
[-0.06326531  0.1         0.07777778] -4093.33110908
[-0.06326531  0.1         0.08888889] -4093.33110908
[-0.06326531  0.1         0.1       ] -4093.33110908
[-0.05918367  0.          0.        ] -4093.33110908
[-0.05918367  0.          0.01111111] -4093.33110908
[-0.05918367  0.          0.02222222] -4093.33110908
[-0.05918367  0.          0.03333333] -4093.33110908
[-0.05918367  0.          0.04444444] -4093.33110908
[-0.05918367  0.          0.05555556] -4093.33110908
[-0.05918367  0.          0.06666667] -4093.33110908
[-0.05918367  0.          0.07777778] -4093.33110908
[-0.05918367  0.          0.08888889] -4093.33110908
[-0.05918367  0.          0.1       ] -4093.33110908
[-0.05918367  0.01111111  0.        ] -4093.33110908
[-0.05918367  0.01111111  0.01111111] -4093.33110908
[-0.05918367  0.01111111  0.02222222] -4093.33110908
[-0.05918367  0.01111111  0.03333333] -4093.33110908
[-0.05918367  0.01111111  0.04

-4093.33110908
[-0.05918367  0.1         0.02222222] -4093.33110908
[-0.05918367  0.1         0.03333333] -4093.33110908
[-0.05918367  0.1         0.04444444] -4093.33110908
[-0.05918367  0.1         0.05555556] -4093.33110908
[-0.05918367  0.1         0.06666667] -4093.33110908
[-0.05918367  0.1         0.07777778] -4093.33110908
[-0.05918367  0.1         0.08888889] -4093.33110908
[-0.05918367  0.1         0.1       ] -4093.33110908
[-0.05510204  0.          0.        ] -4093.33110908
[-0.05510204  0.          0.01111111] -4093.33110908
[-0.05510204  0.          0.02222222] -4093.33110908
[-0.05510204  0.          0.03333333] -4093.33110908
[-0.05510204  0.          0.04444444] -4093.33110908
[-0.05510204  0.          0.05555556] -4093.33110908
[-0.05510204  0.          0.06666667] -4093.33110908
[-0.05510204  0.          0.07777778] -4093.33110908
[-0.05510204  0.          0.08888889] -4093.33110908
[-0.05510204  0.          0.1       ] -4093.33110908
[-0.05510204  0.01111111  0.   


[-0.05510204  0.1         0.08888889] -4093.33110908
[-0.05510204  0.1         0.1       ] -4093.33110908
[-0.05102041  0.          0.        ] -4093.33110908
[-0.05102041  0.          0.01111111] -4093.33110908
[-0.05102041  0.          0.02222222] -4093.33110908
[-0.05102041  0.          0.03333333] -4093.33110908
[-0.05102041  0.          0.04444444] -4093.33110908
[-0.05102041  0.          0.05555556] -4093.33110908
[-0.05102041  0.          0.06666667] -4093.33110908
[-0.05102041  0.          0.07777778] -4093.33110908
[-0.05102041  0.          0.08888889] -4093.33110908
[-0.05102041  0.          0.1       ] -4093.33110908
[-0.05102041  0.01111111  0.        ] -4093.33110908
[-0.05102041  0.01111111  0.01111111] -4093.33110908
[-0.05102041  0.01111111  0.02222222] -4093.33110908
[-0.05102041  0.01111111  0.03333333] -4093.33110908
[-0.05102041  0.01111111  0.04444444] -4093.33110908
[-0.05102041  0.01111111  0.05555556] -4093.33110908
[-0.05102041  0.01111111  0.06666667] -4093.3

[-0.04693878  0.          0.02222222] -4093.33110908
[-0.04693878  0.          0.03333333] -4093.33110908
[-0.04693878  0.          0.04444444] -4093.33110908
[-0.04693878  0.          0.05555556] -4093.33110908
[-0.04693878  0.          0.06666667] -4093.33110908
[-0.04693878  0.          0.07777778] -4093.33110908
[-0.04693878  0.          0.08888889] -4093.33110908
[-0.04693878  0.          0.1       ] -4093.33110908
[-0.04693878  0.01111111  0.        ] -4093.33110908
[-0.04693878  0.01111111  0.01111111] -4093.33110908
[-0.04693878  0.01111111  0.02222222] -4093.33110908
[-0.04693878  0.01111111  0.03333333] -4093.33110908
[-0.04693878  0.01111111  0.04444444] -4093.33110908
[-0.04693878  0.01111111  0.05555556] -4093.33110908
[-0.04693878  0.01111111  0.06666667] -4093.33110908
[-0.04693878  0.01111111  0.07777778] -4093.33110908
[-0.04693878  0.01111111  0.08888889] -4093.33110908
[-0.04693878  0.01111111  0.1       ] -4093.33110908
[-0.04693878  0.02222222  0.        ] -4093.33

[-0.04285714  0.          0.1       ] -4093.33110908
[-0.04285714  0.01111111  0.        ] -4093.33110908
[-0.04285714  0.01111111  0.01111111] -4093.33110908
[-0.04285714  0.01111111  0.02222222] -4093.33110908
[-0.04285714  0.01111111  0.03333333] -4093.33110908
[-0.04285714  0.01111111  0.04444444] -4093.33110908
[-0.04285714  0.01111111  0.05555556] -4093.33110908
[-0.04285714  0.01111111  0.06666667] -4093.33110908
[-0.04285714  0.01111111  0.07777778] -4093.33110908
[-0.04285714  0.01111111  0.08888889] -4093.33110908
[-0.04285714  0.01111111  0.1       ] -4093.33110908
[-0.04285714  0.02222222  0.        ] -4093.33110908
[-0.04285714  0.02222222  0.01111111] -4093.33110908
[-0.04285714  0.02222222  0.02222222] -4093.33110908
[-0.04285714  0.02222222  0.03333333] -4093.33110908
[-0.04285714  0.02222222  0.04444444] -4093.33110908
[-0.04285714  0.02222222  0.05555556] -4093.33110908
[-0.04285714  0.02222222  0.06666667] -4093.33110908
[-0.04285714  0.02222222  0.07777778] -4093.33


[-0.03877551  0.01111111  0.05555556] -4093.33110908
[-0.03877551  0.01111111  0.06666667] -4093.33110908
[-0.03877551  0.01111111  0.07777778] -4093.33110908
[-0.03877551  0.01111111  0.08888889] -4093.33110908
[-0.03877551  0.01111111  0.1       ] -4093.33110908
[-0.03877551  0.02222222  0.        ] -4093.33110908
[-0.03877551  0.02222222  0.01111111] -4093.33110908
[-0.03877551  0.02222222  0.02222222] -4093.33110908
[-0.03877551  0.02222222  0.03333333] -4093.33110908
[-0.03877551  0.02222222  0.04444444] -4093.33110908
[-0.03877551  0.02222222  0.05555556] -4093.33110908
[-0.03877551  0.02222222  0.06666667] -4093.33110908
[-0.03877551  0.02222222  0.07777778] -4093.33110908
[-0.03877551  0.02222222  0.08888889] -4093.33110908
[-0.03877551  0.02222222  0.1       ] -4093.33110908
[-0.03877551  0.03333333  0.        ] -4093.33110908
[-0.03877551  0.03333333  0.01111111] -4093.33110908
[-0.03877551  0.03333333  0.02222222] -4093.33110908
[-0.03877551  0.03333333  0.03333333] -4093.3

[-0.03469388  0.01111111  0.07777778] -4093.33110908
[-0.03469388  0.01111111  0.08888889] -4093.33110908
[-0.03469388  0.01111111  0.1       ] -4093.33110908
[-0.03469388  0.02222222  0.        ] -4093.33110908
[-0.03469388  0.02222222  0.01111111] -4093.33110908
[-0.03469388  0.02222222  0.02222222] -4093.33110908
[-0.03469388  0.02222222  0.03333333] -4093.33110908
[-0.03469388  0.02222222  0.04444444] -4093.33110908
[-0.03469388  0.02222222  0.05555556] -4093.33110908
[-0.03469388  0.02222222  0.06666667] -4093.33110908
[-0.03469388  0.02222222  0.07777778] -4093.33110908
[-0.03469388  0.02222222  0.08888889] -4093.33110908
[-0.03469388  0.02222222  0.1       ] -4093.33110908
[-0.03469388  0.03333333  0.        ] -4093.33110908
[-0.03469388  0.03333333  0.01111111] -4093.33110908
[-0.03469388  0.03333333  0.02222222] -4093.33110908
[-0.03469388  0.03333333  0.03333333] -4093.33110908
[-0.03469388  0.03333333  0.04444444] -4093.33110908
[-0.03469388  0.03333333  0.05555556] -4093.33

[-0.03061224  0.02222222  0.04444444] -4093.33110908
[-0.03061224  0.02222222  0.05555556] -4093.33110908
[-0.03061224  0.02222222  0.06666667] -4093.33110908
[-0.03061224  0.02222222  0.07777778] -4093.33110908
[-0.03061224  0.02222222  0.08888889] -4093.33110908
[-0.03061224  0.02222222  0.1       ] -4093.33110908
[-0.03061224  0.03333333  0.        ] -4093.33110908
[-0.03061224  0.03333333  0.01111111] -4093.33110908
[-0.03061224  0.03333333  0.02222222] -4093.33110908
[-0.03061224  0.03333333  0.03333333] -4093.33110908
[-0.03061224  0.03333333  0.04444444] -4093.33110908
[-0.03061224  0.03333333  0.05555556] -4093.33110908
[-0.03061224  0.03333333  0.06666667] -4093.33110908
[-0.03061224  0.03333333  0.07777778] -4093.33110908
[-0.03061224  0.03333333  0.08888889] -4093.33110908
[-0.03061224  0.03333333  0.1       ] -4093.33110908
[-0.03061224  0.04444444  0.        ] -4093.33110908
[-0.03061224  0.04444444  0.01111111] -4093.33110908
[-0.03061224  0.04444444  0.02222222] -4093.33

-4093.33110908
[-0.02653061  0.02222222  0.01111111] -4093.33110908
[-0.02653061  0.02222222  0.02222222] -4093.33110908
[-0.02653061  0.02222222  0.03333333] -4093.33110908
[-0.02653061  0.02222222  0.04444444] -4093.33110908
[-0.02653061  0.02222222  0.05555556] -4093.33110908
[-0.02653061  0.02222222  0.06666667] -4093.33110908
[-0.02653061  0.02222222  0.07777778] -4093.33110908
[-0.02653061  0.02222222  0.08888889] -4093.33110908
[-0.02653061  0.02222222  0.1       ] -4093.33110908
[-0.02653061  0.03333333  0.        ] -4093.33110908
[-0.02653061  0.03333333  0.01111111] -4093.33110908
[-0.02653061  0.03333333  0.02222222] -4093.33110908
[-0.02653061  0.03333333  0.03333333] -4093.33110908
[-0.02653061  0.03333333  0.04444444] -4093.33110908
[-0.02653061  0.03333333  0.05555556] -4093.33110908
[-0.02653061  0.03333333  0.06666667] -4093.33110908
[-0.02653061  0.03333333  0.07777778] -4093.33110908
[-0.02653061  0.03333333  0.08888889] -4093.33110908
[-0.02653061  0.03333333  0.1  

[-0.02244898  0.01111111  0.08888889] -4093.33110908
[-0.02244898  0.01111111  0.1       ] -4093.33110908
[-0.02244898  0.02222222  0.        ] -4093.33110908
[-0.02244898  0.02222222  0.01111111] -4093.33110908
[-0.02244898  0.02222222  0.02222222] -4093.33110908
[-0.02244898  0.02222222  0.03333333] -4093.33110908
[-0.02244898  0.02222222  0.04444444] -4093.33110908
[-0.02244898  0.02222222  0.05555556] -4093.33110908
[-0.02244898  0.02222222  0.06666667] -4093.33110908
[-0.02244898  0.02222222  0.07777778] -4093.33110908
[-0.02244898  0.02222222  0.08888889] -4093.33110908
[-0.02244898  0.02222222  0.1       ] -4093.33110908
[-0.02244898  0.03333333  0.        ] -4093.33110908
[-0.02244898  0.03333333  0.01111111] -4093.33110908
[-0.02244898  0.03333333  0.02222222] -4093.33110908
[-0.02244898  0.03333333  0.03333333] -4093.33110908
[-0.02244898  0.03333333  0.04444444] -4093.33110908
[-0.02244898  0.03333333  0.05555556] -4093.33110908
[-0.02244898  0.03333333  0.06666667] -4093.33


[-0.01836735  0.          0.1       ] -4093.33110908
[-0.01836735  0.01111111  0.        ] -4093.33110908
[-0.01836735  0.01111111  0.01111111] -4093.33110908
[-0.01836735  0.01111111  0.02222222] -4093.33110908
[-0.01836735  0.01111111  0.03333333] -4093.33110908
[-0.01836735  0.01111111  0.04444444] -4093.33110908
[-0.01836735  0.01111111  0.05555556] -4093.33110908
[-0.01836735  0.01111111  0.06666667] -4093.33110908
[-0.01836735  0.01111111  0.07777778] -4093.33110908
[-0.01836735  0.01111111  0.08888889] -4093.33110908
[-0.01836735  0.01111111  0.1       ] -4093.33110908
[-0.01836735  0.02222222  0.        ] -4093.33110908
[-0.01836735  0.02222222  0.01111111] -4093.33110908
[-0.01836735  0.02222222  0.02222222] -4093.33110908
[-0.01836735  0.02222222  0.03333333] -4093.33110908
[-0.01836735  0.02222222  0.04444444] -4093.33110908
[-0.01836735  0.02222222  0.05555556] -4093.33110908
[-0.01836735  0.02222222  0.06666667] -4093.33110908
[-0.01836735  0.02222222  0.07777778] -4093.3


[-0.01836735  0.07777778  0.08888889] -4093.33110908
[-0.01836735  0.07777778  0.1       ] -4093.33110908
[-0.01836735  0.08888889  0.        ] -4093.33110908
[-0.01836735  0.08888889  0.01111111] -4093.33110908
[-0.01836735  0.08888889  0.02222222] -4093.33110908
[-0.01836735  0.08888889  0.03333333] -4093.33110908
[-0.01836735  0.08888889  0.04444444] -4093.33110908
[-0.01836735  0.08888889  0.05555556] -4093.33110908
[-0.01836735  0.08888889  0.06666667] -4093.33110908
[-0.01836735  0.08888889  0.07777778] -4093.33110908
[-0.01836735  0.08888889  0.08888889] -4093.33110908
[-0.01836735  0.08888889  0.1       ] -4093.33110908
[-0.01836735  0.1         0.        ] -4093.33110908
[-0.01836735  0.1         0.01111111] -4093.33110908
[-0.01836735  0.1         0.02222222] -4093.33110908
[-0.01836735  0.1         0.03333333] -4093.33110908
[-0.01836735  0.1         0.04444444] -4093.33110908
[-0.01836735  0.1         0.05555556] -4093.33110908
[-0.01836735  0.1         0.06666667] -4093.3

[-0.01428571  0.05555556  0.02222222] -4093.33110908
[-0.01428571  0.05555556  0.03333333] -4093.33110908
[-0.01428571  0.05555556  0.04444444] -4093.33110908
[-0.01428571  0.05555556  0.05555556] -4093.33110908
[-0.01428571  0.05555556  0.06666667] -4093.33110908
[-0.01428571  0.05555556  0.07777778] -4093.33110908
[-0.01428571  0.05555556  0.08888889] -4093.33110908
[-0.01428571  0.05555556  0.1       ] -4093.33110908
[-0.01428571  0.06666667  0.        ] -4093.33110908
[-0.01428571  0.06666667  0.01111111] -4093.33110908
[-0.01428571  0.06666667  0.02222222] -4093.33110908
[-0.01428571  0.06666667  0.03333333] -4093.33110908
[-0.01428571  0.06666667  0.04444444] -4093.33110908
[-0.01428571  0.06666667  0.05555556] -4093.33110908
[-0.01428571  0.06666667  0.06666667] -4093.33110908
[-0.01428571  0.06666667  0.07777778] -4093.33110908
[-0.01428571  0.06666667  0.08888889] -4093.33110908
[-0.01428571  0.06666667  0.1       ] -4093.33110908
[-0.01428571  0.07777778  0.        ] -4093.33

[-0.01020408  0.08888889  0.08888889] -4093.33110908
[-0.01020408  0.08888889  0.1       ] -4093.33110908
[-0.01020408  0.1         0.        ] -4093.33110908
[-0.01020408  0.1         0.01111111] -4093.33110908
[-0.01020408  0.1         0.02222222] -4093.33110908
[-0.01020408  0.1         0.03333333] -4093.33110908
[-0.01020408  0.1         0.04444444] -4093.33110908
[-0.01020408  0.1         0.05555556] -4093.33110908
[-0.01020408  0.1         0.06666667] -4093.33110908
[-0.01020408  0.1         0.07777778] -4093.33110908
[-0.01020408  0.1         0.08888889] -4093.33110908
[-0.01020408  0.1         0.1       ] -4093.33110908
[-0.00612245  0.          0.        ] -4093.33110908
[-0.00612245  0.          0.01111111] -4093.33110908
[-0.00612245  0.          0.02222222] -4093.33110908
[-0.00612245  0.          0.03333333] -4093.33110908
[-0.00612245  0.          0.04444444] -4093.33110908
[-0.00612245  0.          0.05555556] -4093.33110908
[-0.00612245  0.          0.06666667] -4093.33

 -4093.33110908
[-0.00612245  0.07777778  0.1       ] -4093.33110908
[-0.00612245  0.08888889  0.        ] -4093.33110908
[-0.00612245  0.08888889  0.01111111] -4093.33110908
[-0.00612245  0.08888889  0.02222222] -4093.33110908
[-0.00612245  0.08888889  0.03333333] -4093.33110908
[-0.00612245  0.08888889  0.04444444] -4093.33110908
[-0.00612245  0.08888889  0.05555556] -4093.33110908
[-0.00612245  0.08888889  0.06666667] -4093.33110908
[-0.00612245  0.08888889  0.07777778] -4093.33110908
[-0.00612245  0.08888889  0.08888889] -4093.33110908
[-0.00612245  0.08888889  0.1       ] -4093.33110908
[-0.00612245  0.1         0.        ] -4093.33110908
[-0.00612245  0.1         0.01111111] -4093.33110908
[-0.00612245  0.1         0.02222222] -4093.33110908
[-0.00612245  0.1         0.03333333] -4093.33110908
[-0.00612245  0.1         0.04444444] -4093.33110908
[-0.00612245  0.1         0.05555556] -4093.33110908
[-0.00612245  0.1         0.06666667] -4093.33110908
[-0.00612245  0.1         0.07

[ 0.00204082  0.03333333  0.08888889] -4093.33110908
[ 0.00204082  0.03333333  0.1       ] -4093.33110908
[ 0.00204082  0.04444444  0.        ] -4093.33110908
[ 0.00204082  0.04444444  0.01111111] -4093.33110908
[ 0.00204082  0.04444444  0.02222222] -4093.33110908
[ 0.00204082  0.04444444  0.03333333] -4093.33110908
[ 0.00204082  0.04444444  0.04444444] -4093.33110908
[ 0.00204082  0.04444444  0.05555556] -4093.33110908
[ 0.00204082  0.04444444  0.06666667] -4093.33110908
[ 0.00204082  0.04444444  0.07777778] -4093.33110908
[ 0.00204082  0.04444444  0.08888889] -4093.33110908
[ 0.00204082  0.04444444  0.1       ] -4093.33110908
[ 0.00204082  0.05555556  0.        ] -4093.33110908
[ 0.00204082  0.05555556  0.01111111] -4093.33110908
[ 0.00204082  0.05555556  0.02222222] -4093.33110908
[ 0.00204082  0.05555556  0.03333333] -4093.33110908
[ 0.00204082  0.05555556  0.04444444] -4093.33110908
[ 0.00204082  0.05555556  0.05555556] -4093.33110908
[ 0.00204082  0.05555556  0.06666667] -4093.33

[ 0.00612245  0.08888889  0.06666667] -4093.33110908
[ 0.00612245  0.08888889  0.07777778] -4093.33110908
[ 0.00612245  0.08888889  0.08888889] -4093.33110908
[ 0.00612245  0.08888889  0.1       ] -4093.33110908
[ 0.00612245  0.1         0.        ] -4093.33110908
[ 0.00612245  0.1         0.01111111] -4093.33110908
[ 0.00612245  0.1         0.02222222] -4093.33110908
[ 0.00612245  0.1         0.03333333] -4093.33110908
[ 0.00612245  0.1         0.04444444] -4093.33110908
[ 0.00612245  0.1         0.05555556] -4093.33110908
[ 0.00612245  0.1         0.06666667] -4093.33110908
[ 0.00612245  0.1         0.07777778] -4093.33110908
[ 0.00612245  0.1         0.08888889] -4093.33110908
[ 0.00612245  0.1         0.1       ] -4093.33110908
[ 0.01020408  0.          0.        ] -4093.33110908
[ 0.01020408  0.          0.01111111] -4093.33110908
[ 0.01020408  0.          0.02222222] -4093.33110908
[ 0.01020408  0.          0.03333333] -4093.33110908
[ 0.01020408  0.          0.04444444] -4093.33


[ 0.01020408  0.08888889  0.06666667] -4093.33110908
[ 0.01020408  0.08888889  0.07777778] -4093.33110908
[ 0.01020408  0.08888889  0.08888889] -4093.33110908
[ 0.01020408  0.08888889  0.1       ] -4093.33110908
[ 0.01020408  0.1         0.        ] -4093.33110908
[ 0.01020408  0.1         0.01111111] -4093.33110908
[ 0.01020408  0.1         0.02222222] -4093.33110908
[ 0.01020408  0.1         0.03333333] -4093.33110908
[ 0.01020408  0.1         0.04444444] -4093.33110908
[ 0.01020408  0.1         0.05555556] -4093.33110908
[ 0.01020408  0.1         0.06666667] -4093.33110908
[ 0.01020408  0.1         0.07777778] -4093.33110908
[ 0.01020408  0.1         0.08888889] -4093.33110908
[ 0.01020408  0.1         0.1       ] -4093.33110908
[ 0.01428571  0.          0.        ] -4093.33110908
[ 0.01428571  0.          0.01111111] -4093.33110908
[ 0.01428571  0.          0.02222222] -4093.33110908
[ 0.01428571  0.          0.03333333] -4093.33110908
[ 0.01428571  0.          0.04444444] -4093.3

-4093.33110908
[ 0.01428571  0.1         0.06666667] -4093.33110908
[ 0.01428571  0.1         0.07777778] -4093.33110908
[ 0.01428571  0.1         0.08888889] -4093.33110908
[ 0.01428571  0.1         0.1       ] -4093.33110908
[ 0.01836735  0.          0.        ] -4093.33110908
[ 0.01836735  0.          0.01111111] -4093.33110908
[ 0.01836735  0.          0.02222222] -4093.33110908
[ 0.01836735  0.          0.03333333] -4093.33110908
[ 0.01836735  0.          0.04444444] -4093.33110908
[ 0.01836735  0.          0.05555556] -4093.33110908
[ 0.01836735  0.          0.06666667] -4093.33110908
[ 0.01836735  0.          0.07777778] -4093.33110908
[ 0.01836735  0.          0.08888889] -4093.33110908
[ 0.01836735  0.          0.1       ] -4093.33110908
[ 0.01836735  0.01111111  0.        ] -4093.33110908
[ 0.01836735  0.01111111  0.01111111] -4093.33110908
[ 0.01836735  0.01111111  0.02222222] -4093.33110908
[ 0.01836735  0.01111111  0.03333333] -4093.33110908
[ 0.01836735  0.01111111  0.044

-4093.33110908
[ 0.01836735  0.05555556  0.1       ] -4093.33110908
[ 0.01836735  0.06666667  0.        ] -4093.33110908
[ 0.01836735  0.06666667  0.01111111] -4093.33110908
[ 0.01836735  0.06666667  0.02222222] -4093.33110908
[ 0.01836735  0.06666667  0.03333333] -4093.33110908
[ 0.01836735  0.06666667  0.04444444] -4093.33110908
[ 0.01836735  0.06666667  0.05555556] -4093.33110908
[ 0.01836735  0.06666667  0.06666667] -4093.33110908
[ 0.01836735  0.06666667  0.07777778] -4093.33110908
[ 0.01836735  0.06666667  0.08888889] -4093.33110908
[ 0.01836735  0.06666667  0.1       ] -4093.33110908
[ 0.01836735  0.07777778  0.        ] -4093.33110908
[ 0.01836735  0.07777778  0.01111111] -4093.33110908
[ 0.01836735  0.07777778  0.02222222] -4093.33110908
[ 0.01836735  0.07777778  0.03333333] -4093.33110908
[ 0.01836735  0.07777778  0.04444444] -4093.33110908
[ 0.01836735  0.07777778  0.05555556] -4093.33110908
[ 0.01836735  0.07777778  0.06666667] -4093.33110908
[ 0.01836735  0.07777778  0.077

-4093.33110908
[ 0.02653061  0.07777778  0.01111111] -4093.33110908
[ 0.02653061  0.07777778  0.02222222] -4093.33110908
[ 0.02653061  0.07777778  0.03333333] -4093.33110908
[ 0.02653061  0.07777778  0.04444444] -4093.33110908
[ 0.02653061  0.07777778  0.05555556] -4093.33110908
[ 0.02653061  0.07777778  0.06666667] -4093.33110908
[ 0.02653061  0.07777778  0.07777778] -4093.33110908
[ 0.02653061  0.07777778  0.08888889] -4093.33110908
[ 0.02653061  0.07777778  0.1       ] -4093.33110908
[ 0.02653061  0.08888889  0.        ] -4093.33110908
[ 0.02653061  0.08888889  0.01111111] -4093.33110908
[ 0.02653061  0.08888889  0.02222222] -4093.33110908
[ 0.02653061  0.08888889  0.03333333] -4093.33110908
[ 0.02653061  0.08888889  0.04444444] -4093.33110908
[ 0.02653061  0.08888889  0.05555556] -4093.33110908
[ 0.02653061  0.08888889  0.06666667] -4093.33110908
[ 0.02653061  0.08888889  0.07777778] -4093.33110908
[ 0.02653061  0.08888889  0.08888889] -4093.33110908
[ 0.02653061  0.08888889  0.1  

[ 0.03061224  0.06666667  0.06666667] -4093.33110908
[ 0.03061224  0.06666667  0.07777778] -4093.33110908
[ 0.03061224  0.06666667  0.08888889] -4093.33110908
[ 0.03061224  0.06666667  0.1       ] -4093.33110908
[ 0.03061224  0.07777778  0.        ] -4093.33110908
[ 0.03061224  0.07777778  0.01111111] -4093.33110908
[ 0.03061224  0.07777778  0.02222222] -4093.33110908
[ 0.03061224  0.07777778  0.03333333] -4093.33110908
[ 0.03061224  0.07777778  0.04444444] -4093.33110908
[ 0.03061224  0.07777778  0.05555556] -4093.33110908
[ 0.03061224  0.07777778  0.06666667] -4093.33110908
[ 0.03061224  0.07777778  0.07777778] -4093.33110908
[ 0.03061224  0.07777778  0.08888889] -4093.33110908
[ 0.03061224  0.07777778  0.1       ] -4093.33110908
[ 0.03061224  0.08888889  0.        ] -4093.33110908
[ 0.03061224  0.08888889  0.01111111] -4093.33110908
[ 0.03061224  0.08888889  0.02222222] -4093.33110908
[ 0.03061224  0.08888889  0.03333333] -4093.33110908
[ 0.03061224  0.08888889  0.04444444] -4093.33

 -4093.33110908
[ 0.03469388  0.04444444  0.05555556] -4093.33110908
[ 0.03469388  0.04444444  0.06666667] -4093.33110908
[ 0.03469388  0.04444444  0.07777778] -4093.33110908
[ 0.03469388  0.04444444  0.08888889] -4093.33110908
[ 0.03469388  0.04444444  0.1       ] -4093.33110908
[ 0.03469388  0.05555556  0.        ] -4093.33110908
[ 0.03469388  0.05555556  0.01111111] -4093.33110908
[ 0.03469388  0.05555556  0.02222222] -4093.33110908
[ 0.03469388  0.05555556  0.03333333] -4093.33110908
[ 0.03469388  0.05555556  0.04444444] -4093.33110908
[ 0.03469388  0.05555556  0.05555556] -4093.33110908
[ 0.03469388  0.05555556  0.06666667] -4093.33110908
[ 0.03469388  0.05555556  0.07777778] -4093.33110908
[ 0.03469388  0.05555556  0.08888889] -4093.33110908
[ 0.03469388  0.05555556  0.1       ] -4093.33110908
[ 0.03469388  0.06666667  0.        ] -4093.33110908
[ 0.03469388  0.06666667  0.01111111] -4093.33110908
[ 0.03469388  0.06666667  0.02222222] -4093.33110908
[ 0.03469388  0.06666667  0.03


[ 0.03877551  0.07777778  0.08888889] -4093.33110908
[ 0.03877551  0.07777778  0.1       ] -4093.33110908
[ 0.03877551  0.08888889  0.        ] -4093.33110908
[ 0.03877551  0.08888889  0.01111111] -4093.33110908
[ 0.03877551  0.08888889  0.02222222] -4093.33110908
[ 0.03877551  0.08888889  0.03333333] -4093.33110908
[ 0.03877551  0.08888889  0.04444444] -4093.33110908
[ 0.03877551  0.08888889  0.05555556] -4093.33110908
[ 0.03877551  0.08888889  0.06666667] -4093.33110908
[ 0.03877551  0.08888889  0.07777778] -4093.33110908
[ 0.03877551  0.08888889  0.08888889] -4093.33110908
[ 0.03877551  0.08888889  0.1       ] -4093.33110908
[ 0.03877551  0.1         0.        ] -4093.33110908
[ 0.03877551  0.1         0.01111111] -4093.33110908
[ 0.03877551  0.1         0.02222222] -4093.33110908
[ 0.03877551  0.1         0.03333333] -4093.33110908
[ 0.03877551  0.1         0.04444444] -4093.33110908
[ 0.03877551  0.1         0.05555556] -4093.33110908
[ 0.03877551  0.1         0.06666667] -4093.3

 -4093.33110908
[ 0.04693878  0.01111111  0.01111111] -4093.33110908
[ 0.04693878  0.01111111  0.02222222] -4093.33110908
[ 0.04693878  0.01111111  0.03333333] -4093.33110908
[ 0.04693878  0.01111111  0.04444444] -4093.33110908
[ 0.04693878  0.01111111  0.05555556] -4093.33110908
[ 0.04693878  0.01111111  0.06666667] -4093.33110908
[ 0.04693878  0.01111111  0.07777778] -4093.33110908
[ 0.04693878  0.01111111  0.08888889] -4093.33110908
[ 0.04693878  0.01111111  0.1       ] -4093.33110908
[ 0.04693878  0.02222222  0.        ] -4093.33110908
[ 0.04693878  0.02222222  0.01111111] -4093.33110908
[ 0.04693878  0.02222222  0.02222222] -4093.33110908
[ 0.04693878  0.02222222  0.03333333] -4093.33110908
[ 0.04693878  0.02222222  0.04444444] -4093.33110908
[ 0.04693878  0.02222222  0.05555556] -4093.33110908
[ 0.04693878  0.02222222  0.06666667] -4093.33110908
[ 0.04693878  0.02222222  0.07777778] -4093.33110908
[ 0.04693878  0.02222222  0.08888889] -4093.33110908
[ 0.04693878  0.02222222  0.1 

 -4093.33110908
[ 0.05102041  0.01111111  0.02222222] -4093.33110908
[ 0.05102041  0.01111111  0.03333333] -4093.33110908
[ 0.05102041  0.01111111  0.04444444] -4093.33110908
[ 0.05102041  0.01111111  0.05555556] -4093.33110908
[ 0.05102041  0.01111111  0.06666667] -4093.33110908
[ 0.05102041  0.01111111  0.07777778] -4093.33110908
[ 0.05102041  0.01111111  0.08888889] -4093.33110908
[ 0.05102041  0.01111111  0.1       ] -4093.33110908
[ 0.05102041  0.02222222  0.        ] -4093.33110908
[ 0.05102041  0.02222222  0.01111111] -4093.33110908
[ 0.05102041  0.02222222  0.02222222] -4093.33110908
[ 0.05102041  0.02222222  0.03333333] -4093.33110908
[ 0.05102041  0.02222222  0.04444444] -4093.33110908
[ 0.05102041  0.02222222  0.05555556] -4093.33110908
[ 0.05102041  0.02222222  0.06666667] -4093.33110908
[ 0.05102041  0.02222222  0.07777778] -4093.33110908
[ 0.05102041  0.02222222  0.08888889] -4093.33110908
[ 0.05102041  0.02222222  0.1       ] -4093.33110908
[ 0.05102041  0.03333333  0.  

-4093.33110908
[ 0.05510204  0.03333333  0.01111111] -4093.33110908
[ 0.05510204  0.03333333  0.02222222] -4093.33110908
[ 0.05510204  0.03333333  0.03333333] -4093.33110908
[ 0.05510204  0.03333333  0.04444444] -4093.33110908
[ 0.05510204  0.03333333  0.05555556] -4093.33110908
[ 0.05510204  0.03333333  0.06666667] -4093.33110908
[ 0.05510204  0.03333333  0.07777778] -4093.33110908
[ 0.05510204  0.03333333  0.08888889] -4093.33110908
[ 0.05510204  0.03333333  0.1       ] -4093.33110908
[ 0.05510204  0.04444444  0.        ] -4093.33110908
[ 0.05510204  0.04444444  0.01111111] -4093.33110908
[ 0.05510204  0.04444444  0.02222222] -4093.33110908
[ 0.05510204  0.04444444  0.03333333] -4093.33110908
[ 0.05510204  0.04444444  0.04444444] -4093.33110908
[ 0.05510204  0.04444444  0.05555556] -4093.33110908
[ 0.05510204  0.04444444  0.06666667] -4093.33110908
[ 0.05510204  0.04444444  0.07777778] -4093.33110908
[ 0.05510204  0.04444444  0.08888889] -4093.33110908
[ 0.05510204  0.04444444  0.1  

[ 0.05918367  0.01111111  0.04444444] -4093.33110908
[ 0.05918367  0.01111111  0.05555556] -4093.33110908
[ 0.05918367  0.01111111  0.06666667] -4093.33110908
[ 0.05918367  0.01111111  0.07777778] -4093.33110908
[ 0.05918367  0.01111111  0.08888889] -4093.33110908
[ 0.05918367  0.01111111  0.1       ] -4093.33110908
[ 0.05918367  0.02222222  0.        ] -4093.33110908
[ 0.05918367  0.02222222  0.01111111] -4093.33110908
[ 0.05918367  0.02222222  0.02222222] -4093.33110908
[ 0.05918367  0.02222222  0.03333333] -4093.33110908
[ 0.05918367  0.02222222  0.04444444] -4093.33110908
[ 0.05918367  0.02222222  0.05555556] -4093.33110908
[ 0.05918367  0.02222222  0.06666667] -4093.33110908
[ 0.05918367  0.02222222  0.07777778] -4093.33110908
[ 0.05918367  0.02222222  0.08888889] -4093.33110908
[ 0.05918367  0.02222222  0.1       ] -4093.33110908
[ 0.05918367  0.03333333  0.        ] -4093.33110908
[ 0.05918367  0.03333333  0.01111111] -4093.33110908
[ 0.05918367  0.03333333  0.02222222] -4093.33

-4093.33110908
[ 0.05918367  0.08888889  0.05555556] -4093.33110908
[ 0.05918367  0.08888889  0.06666667] -4093.33110908
[ 0.05918367  0.08888889  0.07777778] -4093.33110908
[ 0.05918367  0.08888889  0.08888889] -4093.33110908
[ 0.05918367  0.08888889  0.1       ] -4093.33110908
[ 0.05918367  0.1         0.        ] -4093.33110908
[ 0.05918367  0.1         0.01111111] -4093.33110908
[ 0.05918367  0.1         0.02222222] -4093.33110908
[ 0.05918367  0.1         0.03333333] -4093.33110908
[ 0.05918367  0.1         0.04444444] -4093.33110908
[ 0.05918367  0.1         0.05555556] -4093.33110908
[ 0.05918367  0.1         0.06666667] -4093.33110908
[ 0.05918367  0.1         0.07777778] -4093.33110908
[ 0.05918367  0.1         0.08888889] -4093.33110908
[ 0.05918367  0.1         0.1       ] -4093.33110908
[ 0.06326531  0.          0.        ] -4093.33110908
[ 0.06326531  0.          0.01111111] -4093.33110908
[ 0.06326531  0.          0.02222222] -4093.33110908
[ 0.06326531  0.          0.033

 -4093.33110908
[ 0.06326531  0.06666667  0.06666667] -4093.33110908
[ 0.06326531  0.06666667  0.07777778] -4093.33110908
[ 0.06326531  0.06666667  0.08888889] -4093.33110908
[ 0.06326531  0.06666667  0.1       ] -4093.33110908
[ 0.06326531  0.07777778  0.        ] -4093.33110908
[ 0.06326531  0.07777778  0.01111111] -4093.33110908
[ 0.06326531  0.07777778  0.02222222] -4093.33110908
[ 0.06326531  0.07777778  0.03333333] -4093.33110908
[ 0.06326531  0.07777778  0.04444444] -4093.33110908
[ 0.06326531  0.07777778  0.05555556] -4093.33110908
[ 0.06326531  0.07777778  0.06666667] -4093.33110908
[ 0.06326531  0.07777778  0.07777778] -4093.33110908
[ 0.06326531  0.07777778  0.08888889] -4093.33110908
[ 0.06326531  0.07777778  0.1       ] -4093.33110908
[ 0.06326531  0.08888889  0.        ] -4093.33110908
[ 0.06326531  0.08888889  0.01111111] -4093.33110908
[ 0.06326531  0.08888889  0.02222222] -4093.33110908
[ 0.06326531  0.08888889  0.03333333] -4093.33110908
[ 0.06326531  0.08888889  0.04

 -4093.33110908
[ 0.07142857  0.          0.        ] -4093.33110908
[ 0.07142857  0.          0.01111111] -4093.33110908
[ 0.07142857  0.          0.02222222] -4093.33110908
[ 0.07142857  0.          0.03333333] -4093.33110908
[ 0.07142857  0.          0.04444444] -4093.33110908
[ 0.07142857  0.          0.05555556] -4093.33110908
[ 0.07142857  0.          0.06666667] -4093.33110908
[ 0.07142857  0.          0.07777778] -4093.33110908
[ 0.07142857  0.          0.08888889] -4093.33110908
[ 0.07142857  0.          0.1       ] -4093.33110908
[ 0.07142857  0.01111111  0.        ] -4093.33110908
[ 0.07142857  0.01111111  0.01111111] -4093.33110908
[ 0.07142857  0.01111111  0.02222222] -4093.33110908
[ 0.07142857  0.01111111  0.03333333] -4093.33110908
[ 0.07142857  0.01111111  0.04444444] -4093.33110908
[ 0.07142857  0.01111111  0.05555556] -4093.33110908
[ 0.07142857  0.01111111  0.06666667] -4093.33110908
[ 0.07142857  0.01111111  0.07777778] -4093.33110908
[ 0.07142857  0.01111111  0.08

-4093.33110908
[ 0.0755102   0.          0.04444444] -4093.33110908
[ 0.0755102   0.          0.05555556] -4093.33110908
[ 0.0755102   0.          0.06666667] -4093.33110908
[ 0.0755102   0.          0.07777778] -4093.33110908
[ 0.0755102   0.          0.08888889] -4093.33110908
[ 0.0755102  0.         0.1      ] -4093.33110908
[ 0.0755102   0.01111111  0.        ] -4093.33110908
[ 0.0755102   0.01111111  0.01111111] -4093.33110908
[ 0.0755102   0.01111111  0.02222222] -4093.33110908
[ 0.0755102   0.01111111  0.03333333] -4093.33110908
[ 0.0755102   0.01111111  0.04444444] -4093.33110908
[ 0.0755102   0.01111111  0.05555556] -4093.33110908
[ 0.0755102   0.01111111  0.06666667] -4093.33110908
[ 0.0755102   0.01111111  0.07777778] -4093.33110908
[ 0.0755102   0.01111111  0.08888889] -4093.33110908
[ 0.0755102   0.01111111  0.1       ] -4093.33110908
[ 0.0755102   0.02222222  0.        ] -4093.33110908
[ 0.0755102   0.02222222  0.01111111] -4093.33110908
[ 0.0755102   0.02222222  0.022222

 -4093.33110908
[ 0.07959184  0.03333333  0.02222222] -4093.33110908
[ 0.07959184  0.03333333  0.03333333] -4093.33110908
[ 0.07959184  0.03333333  0.04444444] -4093.33110908
[ 0.07959184  0.03333333  0.05555556] -4093.33110908
[ 0.07959184  0.03333333  0.06666667] -4093.33110908
[ 0.07959184  0.03333333  0.07777778] -4093.33110908
[ 0.07959184  0.03333333  0.08888889] -4093.33110908
[ 0.07959184  0.03333333  0.1       ] -4093.33110908
[ 0.07959184  0.04444444  0.        ] -4093.33110908
[ 0.07959184  0.04444444  0.01111111] -4093.33110908
[ 0.07959184  0.04444444  0.02222222] -4093.33110908
[ 0.07959184  0.04444444  0.03333333] -4093.33110908
[ 0.07959184  0.04444444  0.04444444] -4093.33110908
[ 0.07959184  0.04444444  0.05555556] -4093.33110908
[ 0.07959184  0.04444444  0.06666667] -4093.33110908
[ 0.07959184  0.04444444  0.07777778] -4093.33110908
[ 0.07959184  0.04444444  0.08888889] -4093.33110908
[ 0.07959184  0.04444444  0.1       ] -4093.33110908
[ 0.07959184  0.05555556  0.  


[ 0.08367347  0.02222222  0.06666667] -4093.33110908
[ 0.08367347  0.02222222  0.07777778] -4093.33110908
[ 0.08367347  0.02222222  0.08888889] -4093.33110908
[ 0.08367347  0.02222222  0.1       ] -4093.33110908
[ 0.08367347  0.03333333  0.        ] -4093.33110908
[ 0.08367347  0.03333333  0.01111111] -4093.33110908
[ 0.08367347  0.03333333  0.02222222] -4093.33110908
[ 0.08367347  0.03333333  0.03333333] -4093.33110908
[ 0.08367347  0.03333333  0.04444444] -4093.33110908
[ 0.08367347  0.03333333  0.05555556] -4093.33110908
[ 0.08367347  0.03333333  0.06666667] -4093.33110908
[ 0.08367347  0.03333333  0.07777778] -4093.33110908
[ 0.08367347  0.03333333  0.08888889] -4093.33110908
[ 0.08367347  0.03333333  0.1       ] -4093.33110908
[ 0.08367347  0.04444444  0.        ] -4093.33110908
[ 0.08367347  0.04444444  0.01111111] -4093.33110908
[ 0.08367347  0.04444444  0.02222222] -4093.33110908
[ 0.08367347  0.04444444  0.03333333] -4093.33110908
[ 0.08367347  0.04444444  0.04444444] -4093.3

 -4093.33110908
[ 0.0877551   0.          0.07777778] -4093.33110908
[ 0.0877551   0.          0.08888889] -4093.33110908
[ 0.0877551  0.         0.1      ] -4093.33110908
[ 0.0877551   0.01111111  0.        ] -4093.33110908
[ 0.0877551   0.01111111  0.01111111] -4093.33110908
[ 0.0877551   0.01111111  0.02222222] -4093.33110908
[ 0.0877551   0.01111111  0.03333333] -4093.33110908
[ 0.0877551   0.01111111  0.04444444] -4093.33110908
[ 0.0877551   0.01111111  0.05555556] -4093.33110908
[ 0.0877551   0.01111111  0.06666667] -4093.33110908
[ 0.0877551   0.01111111  0.07777778] -4093.33110908
[ 0.0877551   0.01111111  0.08888889] -4093.33110908
[ 0.0877551   0.01111111  0.1       ] -4093.33110908
[ 0.0877551   0.02222222  0.        ] -4093.33110908
[ 0.0877551   0.02222222  0.01111111] -4093.33110908
[ 0.0877551   0.02222222  0.02222222] -4093.33110908
[ 0.0877551   0.02222222  0.03333333] -4093.33110908
[ 0.0877551   0.02222222  0.04444444] -4093.33110908
[ 0.0877551   0.02222222  0.05555


[ 0.09183673  0.06666667  0.02222222] -4093.33110908
[ 0.09183673  0.06666667  0.03333333] -4093.33110908
[ 0.09183673  0.06666667  0.04444444] -4093.33110908
[ 0.09183673  0.06666667  0.05555556] -4093.33110908
[ 0.09183673  0.06666667  0.06666667] -4093.33110908
[ 0.09183673  0.06666667  0.07777778] -4093.33110908
[ 0.09183673  0.06666667  0.08888889] -4093.33110908
[ 0.09183673  0.06666667  0.1       ] -4093.33110908
[ 0.09183673  0.07777778  0.        ] -4093.33110908
[ 0.09183673  0.07777778  0.01111111] -4093.33110908
[ 0.09183673  0.07777778  0.02222222] -4093.33110908
[ 0.09183673  0.07777778  0.03333333] -4093.33110908
[ 0.09183673  0.07777778  0.04444444] -4093.33110908
[ 0.09183673  0.07777778  0.05555556] -4093.33110908
[ 0.09183673  0.07777778  0.06666667] -4093.33110908
[ 0.09183673  0.07777778  0.07777778] -4093.33110908
[ 0.09183673  0.07777778  0.08888889] -4093.33110908
[ 0.09183673  0.07777778  0.1       ] -4093.33110908
[ 0.09183673  0.08888889  0.        ] -4093.3

-4093.33110908
[ 0.09591837  0.03333333  0.06666667] -4093.33110908
[ 0.09591837  0.03333333  0.07777778] -4093.33110908
[ 0.09591837  0.03333333  0.08888889] -4093.33110908
[ 0.09591837  0.03333333  0.1       ] -4093.33110908
[ 0.09591837  0.04444444  0.        ] -4093.33110908
[ 0.09591837  0.04444444  0.01111111] -4093.33110908
[ 0.09591837  0.04444444  0.02222222] -4093.33110908
[ 0.09591837  0.04444444  0.03333333] -4093.33110908
[ 0.09591837  0.04444444  0.04444444] -4093.33110908
[ 0.09591837  0.04444444  0.05555556] -4093.33110908
[ 0.09591837  0.04444444  0.06666667] -4093.33110908
[ 0.09591837  0.04444444  0.07777778] -4093.33110908
[ 0.09591837  0.04444444  0.08888889] -4093.33110908
[ 0.09591837  0.04444444  0.1       ] -4093.33110908
[ 0.09591837  0.05555556  0.        ] -4093.33110908
[ 0.09591837  0.05555556  0.01111111] -4093.33110908
[ 0.09591837  0.05555556  0.02222222] -4093.33110908
[ 0.09591837  0.05555556  0.03333333] -4093.33110908
[ 0.09591837  0.05555556  0.044

(array([[ 0.4098143 ,  0.17675167,  0.244766  ],
        [ 1.18580101,  1.89284009,  0.10532461]]), array([1, 0]))

(1647, 3)

array([1, 2, 0])